# Generated by Django 4.1.6 on 2023-04-06 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 13, 54, 46, 924849, tzinfo=datetime.timezone.utc), verbose_name='Publication date'),
        ),
    ]
